version: '3.8'

name: 'leave-management-system'
services:
  lms-app:
    image: pankhhudi/leavemanagementsystem:latest
    container_name: lms-app
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "8080:8080"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 700m
