name: Leave Management System CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy Docker Image
    runs-on: ubuntu-latest
    env:
      # Docker image name on Docker Hub
      DOCKER_IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/leave-management-system
      # Database credentials from GitHub Secrets
      DB_URL: ${{ secrets.DB_URL }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: 'maven'

      - name: Make Maven wrapper executable
        run: chmod +x mvnw

      - name: Build with Maven (skip tests if needed)
        run: ./mvnw clean verify -DskipTests

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Publish Docker Image
        run: |
          echo "Building Docker image..."
          ./mvnw spring-boot:build-image -DskipTests
          echo "Pushing Docker image to Docker Hub..."
          docker push $DOCKER_IMAGE_NAME
